# Generated by Django 3.1.3 on 2020-11-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=80)),
                ('projectname', models.CharField(max_length=80)),
                ('managername', models.CharField(max_length=80)),
                ('justification', models.TextField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('durationofaccess', models.DurationField()),
                ('awss3bucket', models.CharField(max_length=80)),
            ],
        ),
    ]
