# Generated by Django 3.1.3 on 2020-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REQUESTAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='permissionlevel',
            field=models.CharField(default='Read', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='projectname',
            field=models.CharField(max_length=40),
        ),
    ]
