# Generated by Django 3.1.3 on 2020-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REQUESTAPP', '0002_auto_20201124_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='justification',
            new_name='Justification',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='awss3bucket',
            new_name='Manager',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='projectname',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='managername',
            new_name='S3Bucket',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='request',
            name='durationofaccess',
        ),
        migrations.RemoveField(
            model_name='request',
            name='permissionlevel',
        ),
        migrations.RemoveField(
            model_name='request',
            name='startdate',
        ),
        migrations.AddField(
            model_name='request',
            name='AccessDuration',
            field=models.CharField(default=True, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Permission',
            field=models.CharField(default='Read/Write', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='StartDate',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
    ]
