# Generated by Django 3.1.3 on 2020-11-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REQUESTAPP', '0003_auto_20201125_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='name',
            new_name='Name',
        ),
    ]
